### ISSUE TITLE
Data download button

### ISSUE THREAD

**Issue by LeoFeatherstone** [clockor2/clockor2#116]
I have an external user request to download the plotted data. I agree this would be a super useful feature.

**Comment by Wytamma** [comment]
Does that mean the regression data or the RTT vs date data?

**Comment by LeoFeatherstone** [comment]
Both would indeed be good, but the actual data for the points and groups would be far and away most important. I am imagining 3 columns just like the csv input, and possibly adding columns for heights of BFR trees, clock search groupings etc

**Comment by Wytamma** [comment]
@LeoFeatherstone I added a button to export the raw plotly data. Please reopen if you think should do something else.

**Comment by LeoFeatherstone** [comment]
Hey @Wytamma , thank you very much for handling this. I think this is great for the moment. I have reopened because we should ideally reformat the data as a .csv so users don't have to navigate the nested arrays. This is perfect for the moment though - thanks again.

**Comment by Wytamma** [comment]
We might need separate CSV files for the points and regression data. Or the plot data download button can just download the points and we could have a separate button on the panel to download the the regression data.

**Comment by LeoFeatherstone** [comment]
Definitely - but the priority is the plot data. Users can get the regression data from the screen. I think a .csv for the plot data would be sufficient.

**Comment by Wytamma** [comment]
I’m going to mark this as complete as we have the CSV export button now
