### ISSUE TITLE
:bug: User selected samples not included in download

### ISSUE THREAD

**Issue by Wytamma** [clockor2/clockor2#137]
When you export data from the plot User Selected points are not included as a group.

**Comment by LeoFeatherstone** [comment]
Thanks I'll look at this. Is it that this group specifically is omitted, or the entire clock configuration?

**Comment by Wytamma** [comment]
I already fixed it haha😅 that’s why I assigned myself

**Comment by Wytamma** [comment]
Fixed in v1.6.6
