### ISSUE TITLE
Exported SVGs of RTT plots contain non-vector (raster) objects

### ISSUE THREAD

**Issue by trilisser** [clockor2/clockor2#143]
**Is your feature request related to a problem? Please describe.**
Unlike SVGs of trees, exported SVGs of RTT plots contain non-vector (raster) objects. Maybe it is a bug.

![image](https://github.com/clockor2/clockor2/assets/43595074/39bf7db7-23cf-4dbe-87be-fdf6d016c01d)
_screenshot from Adobe Illustrator_

**Describe the solution you'd like**
Please, make them to be vectors!

**Comment by LeoFeatherstone** [comment]
That seems workable, but if we're doing it that way maybe we can just switch to webGL for really large datasets, thus having an automatically vectorised format for most datasets? I'm still open to paying the subscription if it means a more elegant solution.
I will look for some other options first.

**Comment by Wytamma** [comment]
Solved in v1.7.0

![clockor2 - 2024-02-24T004438 620](https://github.com/clockor2/clockor2/assets/13726005/e8689461-a975-4ec3-8824-e9aa6a062acc)
