### ISSUE TITLE
:bug: Missing dates don't raise error

### ISSUE THREAD

**Issue by Wytamma** [clockor2/clockor2#152]
If you load a csv that is missing dates for a tip then the analysis will happily continue and assign a random date? to the missing tip.

If the tip is missing from the CSV then a error should be raised.

**Comment by LeoFeatherstone** [comment]
Is this only for .csv upload or also for trees?

**Comment by Wytamma** [comment]
I think just for csv

**Comment by Wytamma** [comment]
Here's the example csv with one row missing. The local regression still runs but all the global values are NaN. I'll add a patch that checks if all the tips in the tree are in the CSV file. 
[Uploading dates.csv…]()
