### ISSUE TITLE
:bug: bfr causes reset

### ISSUE THREAD

**Issue by Wytamma** [clockor2/clockor2#91]
When you have user selected points and press best fitting root the user selected points are reset, however, the `Reset` button doesn't disappear. 

Should the BFR be recalculated with user selected values?

**Comment by LeoFeatherstone** [comment]
Thanks @Tamma that's a good spot. We only ever find the bfr w.r.t to the global clock, so no need to recalculate with a new selection. I can address this in the branch including RSS.

**Comment by LeoFeatherstone** [comment]
Ok, I've added a temporary "fix" here whereby there is an automatic rest every time you move to the BFR or otherwise update the `currentData` part of state. In the future I can add a state for user selected clock(s) that one can carry between root states, but for now it's too time costly.
