### ISSUE TITLE
:bug: BFR resets user selected group

### ISSUE THREAD

**Issue by Wytamma** [clockor2/clockor2#96]
User selected group get reset by best fitting root. Could just use the current data model as the starting point of BFR so that the user selected group is preserved?

**Comment by LeoFeatherstone** [comment]
Certainly. I tried this recently and found it to be a bit fiddly? Can we tackle this once we extend the user selected clock feature to allow users to add clocks serially?

**Comment by Wytamma** [comment]
@LeoFeatherstone can you open an issue for this serial user added clock feature?
